### ISSUE TITLE
Need to add required  python-dateutil package 

### ISSUE THREAD

**Issue by sgordon46** [PaloAltoNetworks/pcs-toolbox#52]
https://github.com/PaloAltoNetworks/pcs-toolbox/blob/f01db776e5fb9dea3eae040a5c3fa046b2c2f48f/scripts/pcs_compute_forward_to_siem.py#L18

pip install `python-dateutil` would work, but maybe add this to the requirements.txt

**Comment by tkishel** [comment]
That package is required for the scripts, not the api package, and so is located here:

https://github.com/PaloAltoNetworks/pcs-toolbox/blob/main/scripts/requirements.txt

And documented here:

https://github.com/PaloAltoNetworks/pcs-toolbox/tree/main/scripts#Setup

But maybe that isn't good enough, so open to suggestions ...
