### ISSUE TITLE
pcs_configure.py : PrismaCloudUtility object has no attributes "configure"

### ISSUE THREAD

**Issue by syphax-b** [PaloAltoNetworks/pcs-toolbox#62]
## Describe the bug

Can't setup a settings file using pcs_configure due to a Python error : PrismaCloudUtility object has no attributes "configure"

## Your Environment
- Version used : 4.0.6 
- Python version used : 3.10 (virtual env)

**Comment by tkishel** [comment]
Thanks for reaching out. 

I cannot reproduce this, please provide more details.

```
# scripts tkishel$ pip3 list | grep prismacloud

# scripts tkishel$ pip3 install prismacloud-api
Collecting prismacloud-api
  Using cached prismacloud_api-4.0.6-py3-none-any.whl (28 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from prismacloud-api) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->prismacloud-api) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->prismacloud-api) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->prismacloud-api) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/site-packages (from requests->prismacloud-api) (2.0.12)
Installing collected packages: prismacloud-api
Successfully installed prismacloud-api-4.0.6

# scripts tkishel$ pip3 list | grep prismacloud
prismacloud-api      4.0.6

# scripts tkishel$ python3 --version
Python 3.10.2

# scripts tkishel$ python3 pcs_configure.py 
Configuration File Name:
/Users/tkishel/.prismacloud/credentials.json

Settings:

...
```

**Comment by syphax-b** [comment]
Hello,

It seems that the issue lies on the prismacloud-api version.

I'm using the same env for prismacloud-cli which needs prismacloud-api at 4.0.1, but pcs_configure needs prismacloud-api at 4.0.6 in order to correctly work (e.g find the configure attribute on the PrismaCloudUtility class)

Maybe you should add "prismacloud-api=4.0.6' on the requirements.txt file located in the root?

Anyway, thank you for your hard work :)

Best regards,

Syphax

**Comment by tkishel** [comment]
Adding this package to requirements.txt would result in an infinite loop :) 
Eventually, I'll move the api and scripts into separate repos which will avoid these issues.

I've opened: https://github.com/PaloAltoNetworks/prismacloud-cli/pull/61 to resolve this one.

Thanks for this!
